### ISSUE TITLE
Update instruction to allow for running locally (not through docker)

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.prepare.pacta.indices#85]
Once we merge in this batch, I'll go through and see if I can get it working on bare metal? I think if mostly involves changing some things in the docker-compose, but dealing with variable inheritence across this and #71 open at the samer time is tricky.

_Originally posted by @AlexAxthelm in https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/pull/66#discussion_r1504062099_

**Comment by jdhoffa** [comment]
This repository is fundamentally dependent on building off of a base `workflow.transition.monitor` docker image:
https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/blob/c3502eab84c635e60f5e6748f3b1870c799dd6e6/Dockerfile#L1

At this stage, I don't plan to support an API to run this through RStudio as it would either involve:
* jumping through hoops to figure out how to also run "Transition Monitor" itself through RStudio (e.g. by cloning the relevant repositories and calling `source()` on the scripts)
* adding some `system()` lines in the `.R` script to run the Docker image 

Neither of these options seem to be worth the extra maintenance burden.

If either of you see it differently and wish to assign yourself this ticket then go ahead, otherwise I will close this issue. 

FYI @cjyetman

**Comment by AlexAxthelm** [comment]
Closing as noted above.
